import { useState } from "react";
import { useParams, useNavigate, Link } from "react-router-dom";
import { useAudit, useAudits } from "@/hooks/useAudits";
import { useChecklist } from "@/hooks/useChecklist";
import { useFindings } from "@/hooks/useFindings";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { AuditStatusBadge } from "@/components/badges/AuditStatusBadge";
import { SeverityBadge } from "@/components/badges/SeverityBadge";
import { StatusBadge } from "@/components/badges/StatusBadge";
import { ChecklistTab } from "@/components/audit/ChecklistTab";
import { FindingsTab } from "@/components/audit/FindingsTab";
import { FindingDialog } from "@/components/audit/FindingDialog";
import { Skeleton } from "@/components/ui/skeleton";
import {
  ArrowLeft,
  Building2,
  Target,
  Calendar,
  FileText,
  CheckSquare,
  AlertTriangle,
  Download,
} from "lucide-react";
import type { Database } from "@/integrations/supabase/types";

type Finding = Database["public"]["Tables"]["findings"]["Row"];

export default function AuditDetail() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { data: audit, isLoading: auditLoading } = useAudit(id);
  const { checklistItems, isLoading: checklistLoading, updateChecklistItem } = useChecklist(id);
  const { findings, isLoading: findingsLoading, createFinding, updateFinding, deleteFinding } = useFindings(id);
  
  const [findingDialogOpen, setFindingDialogOpen] = useState(false);
  const [editingFinding, setEditingFinding] = useState<Finding | null>(null);

  const handleExportPDF = async () => {
    // For now, we'll create a simple text export
    // In a future iteration, we can add proper PDF generation
    if (!audit) return;

    const content = `
SECURITY AUDIT REPORT
=====================

Audit Name: ${audit.name}
Client: ${audit.client_name}
Target: ${audit.target || "N/A"}
Status: ${audit.status}
Start Date: ${audit.start_date || "N/A"}
End Date: ${audit.end_date || "N/A"}

EXECUTIVE SUMMARY
-----------------
${audit.description || "No description provided."}

FINDINGS SUMMARY
----------------
Total Findings: ${findings.length}
- Critical: ${findings.filter(f => f.severity === "critical").length}
- High: ${findings.filter(f => f.severity === "high").length}
- Medium: ${findings.filter(f => f.severity === "medium").length}
- Low: ${findings.filter(f => f.severity === "low").length}
- Info: ${findings.filter(f => f.severity === "info").length}

DETAILED FINDINGS
-----------------
${findings.map((f, i) => `
${i + 1}. ${f.title}
   Severity: ${f.severity.toUpperCase()}
   Status: ${f.status}
   Description: ${f.description || "N/A"}
   Affected URL: ${f.affected_url || "N/A"}
   Proof of Concept: ${f.proof_of_concept || "N/A"}
   Remediation: ${f.remediation || "N/A"}
`).join("\n")}

CHECKLIST STATUS
----------------
${checklistItems.map(item => `
[${item.checked ? "X" : " "}] ${item.owasp_code}: ${item.title}
    Notes: ${item.notes || "No notes"}
`).join("\n")}

Report generated by Pentest Tracker
Date: ${new Date().toISOString()}
    `.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${audit.name.replace(/\s+/g, "_")}_Report.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (auditLoading) {
    return (
      <div className="space-y-6">
        <Skeleton className="h-10 w-48" />
        <Skeleton className="h-48" />
        <Skeleton className="h-96" />
      </div>
    );
  }

  if (!audit) {
    return (
      <div className="text-center py-12">
        <h2 className="text-2xl font-bold mb-4">Audit not found</h2>
        <Link to="/audits">
          <Button>Back to Audits</Button>
        </Link>
      </div>
    );
  }

  const checkedCount = checklistItems.filter((item) => item.checked).length;

  return (
    <div className="space-y-6">
      <Button
        variant="ghost"
        onClick={() => navigate("/audits")}
        className="mb-4"
      >
        <ArrowLeft className="w-4 h-4 mr-2" />
        Back to Audits
      </Button>

      {/* Audit Header */}
      <Card className="bg-card/80 backdrop-blur-sm border-border/50">
        <CardHeader>
          <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
            <div>
              <div className="flex items-center gap-3 mb-2">
                <CardTitle className="text-2xl">{audit.name}</CardTitle>
                <AuditStatusBadge status={audit.status} />
              </div>
              <CardDescription className="flex flex-wrap items-center gap-4">
                <span className="flex items-center gap-1">
                  <Building2 className="w-4 h-4" />
                  {audit.client_name}
                </span>
                {audit.target && (
                  <span className="flex items-center gap-1">
                    <Target className="w-4 h-4" />
                    {audit.target}
                  </span>
                )}
                {audit.start_date && (
                  <span className="flex items-center gap-1 font-mono text-xs">
                    <Calendar className="w-4 h-4" />
                    {audit.start_date}
                    {audit.end_date && ` - ${audit.end_date}`}
                  </span>
                )}
              </CardDescription>
            </div>
            <Button onClick={handleExportPDF} variant="outline">
              <Download className="w-4 h-4 mr-2" />
              Export Report
            </Button>
          </div>
          {audit.description && (
            <p className="text-sm text-muted-foreground mt-4 border-t border-border/50 pt-4">
              {audit.description}
            </p>
          )}
        </CardHeader>
      </Card>

      {/* Stats */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <Card className="bg-card/80 backdrop-blur-sm border-border/50">
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                <CheckSquare className="w-5 h-5 text-primary" />
              </div>
              <div>
                <p className="text-2xl font-bold">
                  {checkedCount}/{checklistItems.length}
                </p>
                <p className="text-xs text-muted-foreground">Checklist Progress</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-card/80 backdrop-blur-sm border-border/50">
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-severity-critical/10 flex items-center justify-center">
                <AlertTriangle className="w-5 h-5 text-severity-critical" />
              </div>
              <div>
                <p className="text-2xl font-bold">
                  {findings.filter((f) => f.severity === "critical").length}
                </p>
                <p className="text-xs text-muted-foreground">Critical Findings</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-card/80 backdrop-blur-sm border-border/50">
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-severity-high/10 flex items-center justify-center">
                <AlertTriangle className="w-5 h-5 text-severity-high" />
              </div>
              <div>
                <p className="text-2xl font-bold">
                  {findings.filter((f) => f.severity === "high").length}
                </p>
                <p className="text-xs text-muted-foreground">High Findings</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-card/80 backdrop-blur-sm border-border/50">
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-status-open/10 flex items-center justify-center">
                <FileText className="w-5 h-5 text-status-open" />
              </div>
              <div>
                <p className="text-2xl font-bold">
                  {findings.filter((f) => f.status === "open").length}
                </p>
                <p className="text-xs text-muted-foreground">Open Findings</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Tabs */}
      <Tabs defaultValue="checklist" className="space-y-4">
        <TabsList className="bg-muted/50">
          <TabsTrigger value="checklist" className="data-[state=active]:bg-primary data-[state=active]:text-primary-foreground">
            <CheckSquare className="w-4 h-4 mr-2" />
            OWASP Checklist
          </TabsTrigger>
          <TabsTrigger value="findings" className="data-[state=active]:bg-primary data-[state=active]:text-primary-foreground">
            <AlertTriangle className="w-4 h-4 mr-2" />
            Findings ({findings.length})
          </TabsTrigger>
        </TabsList>

        <TabsContent value="checklist">
          <ChecklistTab
            items={checklistItems}
            isLoading={checklistLoading}
            onUpdateItem={updateChecklistItem.mutate}
          />
        </TabsContent>

        <TabsContent value="findings">
          <FindingsTab
            findings={findings}
            isLoading={findingsLoading}
            onAddFinding={() => {
              setEditingFinding(null);
              setFindingDialogOpen(true);
            }}
            onEditFinding={(finding) => {
              setEditingFinding(finding);
              setFindingDialogOpen(true);
            }}
            onDeleteFinding={(id) => deleteFinding.mutate(id)}
          />
        </TabsContent>
      </Tabs>

      {/* Finding Dialog */}
      <FindingDialog
        open={findingDialogOpen}
        onOpenChange={setFindingDialogOpen}
        auditId={audit.id}
        finding={editingFinding}
        onSave={(data) => {
          if (editingFinding) {
            updateFinding.mutate({ id: editingFinding.id, ...data });
          } else {
            createFinding.mutate({ 
              audit_id: audit.id,
              title: data.title!,
              description: data.description,
              severity: data.severity,
              status: data.status,
              proof_of_concept: data.proof_of_concept,
              remediation: data.remediation,
              affected_url: data.affected_url,
              cvss_score: data.cvss_score,
            });
          }
          setFindingDialogOpen(false);
        }}
      />
    </div>
  );
}
